### ISSUE TITLE
Error export flutter

### ISSUE THREAD

**Issue by engdanilosouza** [TheTomTom3901/flutter-export#1]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Specifications (please complete the following information):**
 - OS: [e.g. Mac]
 - XD Version [e.g. 22.0.12.12]
 - Plugin Version [e.g. 1.0.0]

**Additional context**

**Comment by appsbytom** [comment]
Have you got any information as to what the issue is? You have not filled out any of the needed information, if not this will be closed
