### ISSUE TITLE
Exporting failed io.failed

### ISSUE THREAD

**Issue by insinfo** [TheTomTom3901/flutter-export#2]
Exporting failed io.failed

 - OS: Windows
 - XD Version: 28.1.12.3 
 - Plugin Version: last
![image](https://user-images.githubusercontent.com/12227024/76865196-1dc78780-6841-11ea-9cea-ecf376eb2c78.png)
![image](https://user-images.githubusercontent.com/12227024/76865467-87479600-6841-11ea-82f8-4ec11ae1a690.png)

![image](https://user-images.githubusercontent.com/12227024/76865378-6717d700-6841-11ea-9d33-1e568e9cffc5.png)
![image](https://user-images.githubusercontent.com/12227024/76865402-6ed77b80-6841-11ea-8d30-9cfaeda1f1ca.png)

**Comment by appsbytom** [comment]
@insinfo are you able to check the console logs and send exactly what it shows, `io.failed` is not very descriptive so wondering if the console has more details? Im not sure the steps for Windows but on MacOS its as below

![image](https://user-images.githubusercontent.com/22203095/76873056-2a5dd700-6865-11ea-9b66-8c37b33a0d84.png)

**Comment by appsbytom** [comment]
Closing as no further details were given
