### ISSUE TITLE
Flutter-export error

### ISSUE THREAD

**Issue by Denizyucel** [TheTomTom3901/flutter-export#3]
![pluggin-error](https://user-images.githubusercontent.com/46918333/78030856-6d42a300-736b-11ea-9ee5-42d3416c68a1.PNG)

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Specifications (please complete the following information):**
 - OS: [e.g. Mac]
 - XD Version [e.g. 22.0.12.12]
 - Plugin Version [e.g. 1.0.0]

**Additional context**

**Comment by appsbytom** [comment]
Can you give more details on this error? None of the fields are filled which makes finding and addressing the issue harder

**Comment by appsbytom** [comment]
No details were given. Closed
