### ISSUE TITLE
export imag

### ISSUE THREAD

**Issue by MehmetAliErcan** [TheTomTom3901/flutter-export#5]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Specifications (please complete the following information):**
 - OS: [e.g. Mac]
 - XD Version [e.g. 22.0.12.12]
 - Plugin Version [e.g. 1.0.0]

**Additional context**

**Comment by appsbytom** [comment]
Closed due to lacking details
